# Generated by Django 6.0.3 on 2026-03-30 18:18

import csv_files.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('file', models.FileField(upload_to=csv_files.models.csv_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='CSV-файл')),
                ('header_in_first_line', models.BooleanField(default=True, verbose_name='Заголовок колонок в первой строке')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'CSV-файл',
                'verbose_name_plural': 'CSV-файлы',
            },
        ),
        migrations.CreateModel(
            name='DistortableInCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('column_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер колонки, которую искажать')),
                ('column_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок колонки')),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_files.csvfile', verbose_name='CSV-файл')),
            ],
            options={
                'verbose_name': 'Изменяемая колонка в CSV-файле',
                'verbose_name_plural': 'Изменяемые колонки в CSV-файлах',
            },
        ),
    ]
