# Generated by Django 6.0.3 on 2026-03-29 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0005_alter_script_options_alter_distortable_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('file', models.FileField(upload_to='csv_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='CSV-файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'CSV-файл',
                'verbose_name_plural': 'CSV-файлы',
            },
        ),
        migrations.CreateModel(
            name='DistortableInCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('column', models.CharField(max_length=100, verbose_name='Колонка')),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_files.csvfile', verbose_name='CSV-файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Изменяемая колонка в CSV-файле',
                'verbose_name_plural': 'Изменяемые колонки в CSV-файлах',
            },
        ),
    ]
