# Generated by Django 6.0.3 on 2026-03-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_files', '0002_remove_distortableincsv_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distortableincsv',
            name='title',
        ),
    ]
