# Generated by Django 6.0.3 on 2026-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_files', '0003_remove_distortableincsv_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distortableincsv',
            name='column',
            field=models.PositiveIntegerField(verbose_name='Колонка, которую искажать'),
        ),
    ]
