# Generated by Django 6.0.3 on 2026-03-29 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_files', '0004_alter_distortableincsv_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distortableincsv',
            name='column',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='header_in_first_line',
            field=models.BooleanField(default=True, verbose_name='Заголовок колонок в первой строке'),
        ),
        migrations.AddField(
            model_name='distortableincsv',
            name='column_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='CSV-файл'),
        ),
        migrations.AddField(
            model_name='distortableincsv',
            name='column_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер колонки, которую искажать'),
            preserve_default=False,
        ),
    ]
