# Generated by Django 6.0.3 on 2026-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_files', '0005_remove_distortableincsv_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distortableincsv',
            name='column_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок колонки'),
        ),
    ]
