# Generated by Django 6.0.3 on 2026-03-30 09:27

import csv_files.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_files', '0006_alter_distortableincsv_column_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to=csv_files.models.csv_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='CSV-файл'),
        ),
    ]
