# Generated by Django 6.0.3 on 2026-03-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='unlocked',
            field=models.BooleanField(default=False, verbose_name='Предохранитель снят'),
        ),
    ]
