# Generated by Django 6.0.3 on 2026-03-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_unlocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
    ]
