# Generated by Django 6.0.3 on 2026-03-30 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('educational_facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=1000, verbose_name='Операционная система')),
                ('number_of_variants', models.IntegerField(default=35, validators=[django.core.validators.MinValueValidator(1)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='courses.course', verbose_name='Курс')),
                ('educational_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='educational_facilities.educationalfacility', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Опции',
                'verbose_name_plural': 'Опции',
            },
        ),
    ]
