# Generated by Django 6.0.3 on 2026-03-29 14:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educational_facilities', '0004_alter_educationalfacility_unlocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_variants', models.IntegerField(default=35, validators=[django.core.validators.MinValueValidator(1)])),
                ('educational_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educational_facilities.educationalfacility', verbose_name='Учебное заведение')),
            ],
        ),
    ]
