# Generated by Django 6.0.3 on 2026-03-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating_systems', '0001_initial'),
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='operating_systems.operatingsystem', verbose_name='Операционная система'),
        ),
    ]
