# Generated by Django 6.0.3 on 2026-03-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Опции', 'verbose_name_plural': 'Опции'},
        ),
    ]
