# Generated by Django 6.0.3 on 2026-03-30 18:18

import django.core.validators
import django.db.models.deletion
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csv_files', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('to_be_distorted', models.BooleanField(default=True, verbose_name='Искажать')),
                ('column_number', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Для искажения найти в колонке')),
                ('image', models.ImageField(upload_to=images.models.task_image_path, verbose_name='Изображение')),
                ('csv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='csv_files.csvfile', verbose_name='CSV-файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
