# Generated by Django 6.0.3 on 2026-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='to_be_distorted',
            field=models.BooleanField(default=False, verbose_name='Искажать'),
        ),
    ]
