# Generated by Django 6.0.3 on 2026-03-30 09:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_files', '0007_alter_csvfile_file'),
        ('images', '0003_alter_img_to_be_distorted'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='column_number',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Для искажения найти в колонке'),
        ),
        migrations.AddField(
            model_name='img',
            name='csv',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='csv_files.csvfile', verbose_name='CSV-файл'),
            preserve_default=False,
        ),
    ]
