# Generated by Django 6.0.3 on 2026-03-29 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, verbose_name='Код')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professions.profession', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
