# Generated by Django 6.0.3 on 2026-03-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educational_facilities', '0001_initial'),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.CharField(blank=True, default='', max_length=100, verbose_name='Код')),
                ('instruction_on_room_preparation', models.TextField(verbose_name='Как оснастить кабинет')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professions.profession', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CoursesInFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='courses.course', verbose_name='Курс')),
                ('educational_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='educational_facilities.educationalfacility', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Курс в образовательном учреждении',
                'verbose_name_plural': 'Курсы в образовательных учреждениях',
            },
        ),
    ]
