# Generated by Django 6.0.3 on 2026-03-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unlocked',
            field=models.BooleanField(default=False, verbose_name='Предохранитель снят'),
        ),
    ]
