# Generated by Django 6.0.3 on 2026-03-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_unlocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Код'),
        ),
    ]
