# Generated by Django 6.0.3 on 2026-03-30 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_comment_alter_course_created_at_and_more'),
        ('educational_facilities', '0004_alter_educationalfacility_unlocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesInFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='Курс')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educational_facilities.educationalfacility', verbose_name='Образовательное учреждение')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
