# Generated by Django 6.0.3 on 2026-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursesinfacilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesinfacilities',
            options={'verbose_name': 'Курс в образовательном учреждении', 'verbose_name_plural': 'Курсы в образовательных учреждениях'},
        ),
        migrations.AddField(
            model_name='course',
            name='instruction_on_room_preparation',
            field=models.TextField(default=1, verbose_name='Как оснастить кабинет'),
            preserve_default=False,
        ),
    ]
