# Generated by Django 6.0.3 on 2026-03-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureListForAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('archive', models.BooleanField(default=False, verbose_name='Архив')),
                ('os', models.CharField(max_length=1000, verbose_name='Операционная система')),
                ('real_name', models.CharField(blank=True, default='', max_length=1000, verbose_name='Наименование для системного администратора')),
                ('download_link', models.CharField(blank=True, default='', max_length=1000, verbose_name='Ссылка для скачивания')),
                ('instruction', models.TextField(blank=True, default='', verbose_name='Инструкция по установке')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureListForPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('archive', models.BooleanField(default=False, verbose_name='Архив')),
                ('os', models.CharField(max_length=1000, verbose_name='Операционная система')),
                ('general_name', models.CharField(blank=True, default='Обобщенное наименование дя паспорта ЦПДЭ', max_length=1000, verbose_name='')),
                ('okpd2', models.CharField(blank=True, default='', max_length=1000, verbose_name='ОКПД 2')),
                ('manufacturer', models.CharField(blank=True, default='', verbose_name='Производитель')),
                ('country', models.CharField(blank=True, default='', verbose_name='Страна')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
