# Generated by Django 6.0.3 on 2026-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInInfrastructureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('real_name', models.CharField(blank=True, default='Наименование для системного администратора', max_length=1000, verbose_name='')),
                ('general_name', models.CharField(blank=True, default='Обобщенное наименование дя паспорта ЦПДЭ', max_length=1000, verbose_name='')),
                ('okpd2', models.CharField(blank=True, default='', max_length=1000, verbose_name='ОКПД 2')),
                ('manufacturer', models.CharField(blank=True, default='', verbose_name='Производитель')),
                ('country', models.CharField(blank=True, default='', verbose_name='Страна')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
