# Generated by Django 6.0.3 on 2026-03-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа заданий',
                'verbose_name_plural': 'Группы заданий',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.CharField(blank=True, default='', max_length=100, verbose_name='Код')),
                ('archive', models.BooleanField(default=False, verbose_name='Архив')),
                ('variant', models.CharField(blank=True, default='', max_length=100, verbose_name='Вариант')),
                ('threshold', models.BooleanField(default=False, verbose_name='Рубежная аттестация')),
                ('real_demo_exam', models.BooleanField(default=False, verbose_name='Реальный пример с демонстрационного экзамена')),
                ('exam', models.BooleanField(default=False, verbose_name='Экзамен')),
                ('inspection', models.BooleanField(default=False, verbose_name='Контрольная работа')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='courses.course', verbose_name='Курс')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.taskgroup', verbose_name='Группа заданий')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('to_be_distorted', models.BooleanField(default=True, verbose_name='Искажать')),
                ('text', models.TextField(verbose_name='Скрипт')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Скрипт',
                'verbose_name_plural': 'Скрипты',
            },
        ),
        migrations.CreateModel(
            name='PrintableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('text', models.TextField(verbose_name='Текст')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Распечатываемое задание',
                'verbose_name_plural': 'Распечатываемое задание',
            },
        ),
        migrations.CreateModel(
            name='Distortable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('word', models.CharField(max_length=1000)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Искажаемое',
                'verbose_name_plural': 'Искажаемое',
            },
        ),
        migrations.CreateModel(
            name='TaskAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', related_query_name='author', to='employees.employee', verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Автор задания',
                'verbose_name_plural': 'Авторы заданий',
            },
        ),
    ]
