# Generated by Django 6.0.3 on 2026-03-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, default='', max_length=100, verbose_name='Код')),
                ('variant', models.CharField(blank=True, max_length=100, verbose_name='Вариант')),
                ('threshold', models.BooleanField(default=False, verbose_name='Рубежная аттестация')),
                ('real_demo_exam', models.BooleanField(default=False, verbose_name='Реальный пример с демонстрационного экзамена')),
                ('exam', models.BooleanField(default=False, verbose_name='Экзамен')),
                ('inspection', models.BooleanField(default=False, verbose_name='Контрольная работа')),
                ('archive', models.BooleanField(default=False, verbose_name='Архив')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
