# Generated by Django 6.0.3 on 2026-03-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Группа заданий',
                'verbose_name_plural': 'Группы заданий',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вариант'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.taskgroup', verbose_name='Группа заданий'),
        ),
    ]
