# Generated by Django 6.0.3 on 2026-03-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_degree_alter_employee_first_name_and_more'),
        ('tasks', '0003_alter_task_comment_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', related_query_name='author', to='employees.employee', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='taskauthor',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задания'),
        ),
        migrations.CreateModel(
            name='Distortable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('word', models.CharField(max_length=1000)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задания')),
            ],
            options={
                'verbose_name': 'Искажаемое',
                'verbose_name_plural': 'Искажаемое',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('text', models.TextField(verbose_name='Скрипт')),
                ('to_be_distorted', models.BooleanField(default=False, verbose_name='Искажать')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задания')),
            ],
            options={
                'verbose_name': 'SQL-скрипт',
                'verbose_name_plural': 'SQL-скрипты',
            },
        ),
    ]
