# Generated by Django 6.0.3 on 2026-03-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskauthor_author_alter_taskauthor_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'verbose_name': 'Скрипт', 'verbose_name_plural': 'Скрипты'},
        ),
        migrations.AlterField(
            model_name='distortable',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='script',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='taskauthor',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание'),
        ),
    ]
