# Generated by Django 6.0.3 on 2026-03-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_script_options_alter_distortable_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('text', models.TextField(verbose_name='Текст')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Распечатываемое задание',
                'verbose_name_plural': 'Распечатываемое задание',
            },
        ),
    ]
