# Generated by Django 6.0.3 on 2026-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_printabletask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='to_be_distorted',
            field=models.BooleanField(default=True, verbose_name='Искажать'),
        ),
    ]
