# Generated by Django 6.0.3 on 2026-03-29 11:43

import django.db.models.deletion
import educational_facilities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Снять предохранитель')),
                ('superior_body_1', models.CharField(blank=True, max_length=1000, verbose_name='Вышестоящая организация 1')),
                ('superior_body_2', models.CharField(blank=True, max_length=1000, verbose_name='Вышестоящая организация 2')),
                ('formation_type', models.CharField(blank=True, max_length=1000, verbose_name='Организационно-правовая форма')),
                ('full_name', models.CharField(blank=True, max_length=1000, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=1000, verbose_name='Краткое наименование')),
                ('logo', models.ImageField(blank=True, upload_to=educational_facilities.models.task_facility_path, verbose_name='Логотип')),
                ('front_page_template', models.TextField(blank=True, verbose_name='Титульный лист')),
                ('chairperson', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='chairpeople', related_query_name='chairperson', to='employees.employee', verbose_name='Председатель ПЦК')),
                ('deputy_director', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='deputy_directors', related_query_name='deputy_director', to='employees.employee', verbose_name='Заместитель директора по УМР')),
            ],
            options={
                'verbose_name': 'Образовательная организация',
                'verbose_name_plural': 'Образовательные организации',
            },
        ),
    ]
