# Generated by Django 6.0.3 on 2026-03-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalfacility',
            name='front_page_template',
            field=models.TextField(blank=True, verbose_name='Шаблон титульного листа'),
        ),
    ]
