# Generated by Django 6.0.3 on 2026-03-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_facilities', '0002_alter_educationalfacility_front_page_template'),
        ('employees', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalfacility',
            name='chairperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chairpeople', related_query_name='chairperson', to='employees.employee', verbose_name='Председатель ПЦК'),
        ),
        migrations.AlterField(
            model_name='educationalfacility',
            name='deputy_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deputy_directors', related_query_name='deputy_director', to='employees.employee', verbose_name='Заместитель директора по УМР'),
        ),
    ]
