# Generated by Django 6.0.3 on 2026-03-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_facilities', '0003_alter_educationalfacility_chairperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalfacility',
            name='unlocked',
            field=models.BooleanField(default=False, verbose_name='Предохранитель снят'),
        ),
    ]
