# Generated by Django 6.0.3 on 2026-03-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Предохранитель снят')),
                ('slug', models.CharField(blank=True, default='', max_length=100, verbose_name='Код')),
                ('major', models.CharField(max_length=1000, verbose_name='Направленность')),
                ('name', models.CharField(max_length=1000, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
    ]
